# Generated by Django 4.1 on 2023-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shippingaddress_options_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
