# Generated by Django 5.1.5 on 2025-02-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/placeholder.png', null=True, upload_to='products/'),
        ),
    ]
